###################################################################

# Created by write_script -format dctcl on Wed Nov 11 20:02:42 2015

###################################################################

# Set the current_design #
current_design DPA

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max slow -max_library slow\
                         -min fast -min_library fast
set_wire_load_model -name tsmc13_wl10 -library slow
set_local_link_library {slow.db}
set_fix_multiple_port_nets -all
set_max_transition 1 [current_design]
set_max_fanout 50 [current_design]
set_max_area 0
set_load -pin_load 1 [get_ports {IM_A[19]}]
set_load -pin_load 1 [get_ports {IM_A[18]}]
set_load -pin_load 1 [get_ports {IM_A[17]}]
set_load -pin_load 1 [get_ports {IM_A[16]}]
set_load -pin_load 1 [get_ports {IM_A[15]}]
set_load -pin_load 1 [get_ports {IM_A[14]}]
set_load -pin_load 1 [get_ports {IM_A[13]}]
set_load -pin_load 1 [get_ports {IM_A[12]}]
set_load -pin_load 1 [get_ports {IM_A[11]}]
set_load -pin_load 1 [get_ports {IM_A[10]}]
set_load -pin_load 1 [get_ports {IM_A[9]}]
set_load -pin_load 1 [get_ports {IM_A[8]}]
set_load -pin_load 1 [get_ports {IM_A[7]}]
set_load -pin_load 1 [get_ports {IM_A[6]}]
set_load -pin_load 1 [get_ports {IM_A[5]}]
set_load -pin_load 1 [get_ports {IM_A[4]}]
set_load -pin_load 1 [get_ports {IM_A[3]}]
set_load -pin_load 1 [get_ports {IM_A[2]}]
set_load -pin_load 1 [get_ports {IM_A[1]}]
set_load -pin_load 1 [get_ports {IM_A[0]}]
set_load -pin_load 1 [get_ports {IM_D[23]}]
set_load -pin_load 1 [get_ports {IM_D[22]}]
set_load -pin_load 1 [get_ports {IM_D[21]}]
set_load -pin_load 1 [get_ports {IM_D[20]}]
set_load -pin_load 1 [get_ports {IM_D[19]}]
set_load -pin_load 1 [get_ports {IM_D[18]}]
set_load -pin_load 1 [get_ports {IM_D[17]}]
set_load -pin_load 1 [get_ports {IM_D[16]}]
set_load -pin_load 1 [get_ports {IM_D[15]}]
set_load -pin_load 1 [get_ports {IM_D[14]}]
set_load -pin_load 1 [get_ports {IM_D[13]}]
set_load -pin_load 1 [get_ports {IM_D[12]}]
set_load -pin_load 1 [get_ports {IM_D[11]}]
set_load -pin_load 1 [get_ports {IM_D[10]}]
set_load -pin_load 1 [get_ports {IM_D[9]}]
set_load -pin_load 1 [get_ports {IM_D[8]}]
set_load -pin_load 1 [get_ports {IM_D[7]}]
set_load -pin_load 1 [get_ports {IM_D[6]}]
set_load -pin_load 1 [get_ports {IM_D[5]}]
set_load -pin_load 1 [get_ports {IM_D[4]}]
set_load -pin_load 1 [get_ports {IM_D[3]}]
set_load -pin_load 1 [get_ports {IM_D[2]}]
set_load -pin_load 1 [get_ports {IM_D[1]}]
set_load -pin_load 1 [get_ports {IM_D[0]}]
set_load -pin_load 1 [get_ports IM_WEN]
set_load -pin_load 1 [get_ports {CR_A[8]}]
set_load -pin_load 1 [get_ports {CR_A[7]}]
set_load -pin_load 1 [get_ports {CR_A[6]}]
set_load -pin_load 1 [get_ports {CR_A[5]}]
set_load -pin_load 1 [get_ports {CR_A[4]}]
set_load -pin_load 1 [get_ports {CR_A[3]}]
set_load -pin_load 1 [get_ports {CR_A[2]}]
set_load -pin_load 1 [get_ports {CR_A[1]}]
set_load -pin_load 1 [get_ports {CR_A[0]}]
create_clock [get_ports clk]  -period 1000  -waveform {0 500}
set_clock_latency 1  [get_clocks clk]
set_clock_uncertainty 1  [get_clocks clk]
set_dont_touch_network [get_clocks clk]
set_input_delay -clock clk  1  [get_ports reset]
set_input_delay -clock clk  1  [get_ports {IM_Q[23]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[22]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[21]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[20]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[19]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[18]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[17]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[16]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[15]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[14]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[13]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[12]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[11]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[10]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[9]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[8]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[7]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[6]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[5]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[4]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[3]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[2]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[1]}]
set_input_delay -clock clk  1  [get_ports {IM_Q[0]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[12]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[11]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[10]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[9]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[8]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[7]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[6]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[5]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[4]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[3]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[2]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[1]}]
set_input_delay -clock clk  1  [get_ports {CR_Q[0]}]
set_output_delay -clock clk  1  [get_ports {IM_A[19]}]
set_output_delay -clock clk  1  [get_ports {IM_A[18]}]
set_output_delay -clock clk  1  [get_ports {IM_A[17]}]
set_output_delay -clock clk  1  [get_ports {IM_A[16]}]
set_output_delay -clock clk  1  [get_ports {IM_A[15]}]
set_output_delay -clock clk  1  [get_ports {IM_A[14]}]
set_output_delay -clock clk  1  [get_ports {IM_A[13]}]
set_output_delay -clock clk  1  [get_ports {IM_A[12]}]
set_output_delay -clock clk  1  [get_ports {IM_A[11]}]
set_output_delay -clock clk  1  [get_ports {IM_A[10]}]
set_output_delay -clock clk  1  [get_ports {IM_A[9]}]
set_output_delay -clock clk  1  [get_ports {IM_A[8]}]
set_output_delay -clock clk  1  [get_ports {IM_A[7]}]
set_output_delay -clock clk  1  [get_ports {IM_A[6]}]
set_output_delay -clock clk  1  [get_ports {IM_A[5]}]
set_output_delay -clock clk  1  [get_ports {IM_A[4]}]
set_output_delay -clock clk  1  [get_ports {IM_A[3]}]
set_output_delay -clock clk  1  [get_ports {IM_A[2]}]
set_output_delay -clock clk  1  [get_ports {IM_A[1]}]
set_output_delay -clock clk  1  [get_ports {IM_A[0]}]
set_output_delay -clock clk  1  [get_ports {IM_D[23]}]
set_output_delay -clock clk  1  [get_ports {IM_D[22]}]
set_output_delay -clock clk  1  [get_ports {IM_D[21]}]
set_output_delay -clock clk  1  [get_ports {IM_D[20]}]
set_output_delay -clock clk  1  [get_ports {IM_D[19]}]
set_output_delay -clock clk  1  [get_ports {IM_D[18]}]
set_output_delay -clock clk  1  [get_ports {IM_D[17]}]
set_output_delay -clock clk  1  [get_ports {IM_D[16]}]
set_output_delay -clock clk  1  [get_ports {IM_D[15]}]
set_output_delay -clock clk  1  [get_ports {IM_D[14]}]
set_output_delay -clock clk  1  [get_ports {IM_D[13]}]
set_output_delay -clock clk  1  [get_ports {IM_D[12]}]
set_output_delay -clock clk  1  [get_ports {IM_D[11]}]
set_output_delay -clock clk  1  [get_ports {IM_D[10]}]
set_output_delay -clock clk  1  [get_ports {IM_D[9]}]
set_output_delay -clock clk  1  [get_ports {IM_D[8]}]
set_output_delay -clock clk  1  [get_ports {IM_D[7]}]
set_output_delay -clock clk  1  [get_ports {IM_D[6]}]
set_output_delay -clock clk  1  [get_ports {IM_D[5]}]
set_output_delay -clock clk  1  [get_ports {IM_D[4]}]
set_output_delay -clock clk  1  [get_ports {IM_D[3]}]
set_output_delay -clock clk  1  [get_ports {IM_D[2]}]
set_output_delay -clock clk  1  [get_ports {IM_D[1]}]
set_output_delay -clock clk  1  [get_ports {IM_D[0]}]
set_output_delay -clock clk  1  [get_ports IM_WEN]
set_output_delay -clock clk  1  [get_ports {CR_A[8]}]
set_output_delay -clock clk  1  [get_ports {CR_A[7]}]
set_output_delay -clock clk  1  [get_ports {CR_A[6]}]
set_output_delay -clock clk  1  [get_ports {CR_A[5]}]
set_output_delay -clock clk  1  [get_ports {CR_A[4]}]
set_output_delay -clock clk  1  [get_ports {CR_A[3]}]
set_output_delay -clock clk  1  [get_ports {CR_A[2]}]
set_output_delay -clock clk  1  [get_ports {CR_A[1]}]
set_output_delay -clock clk  1  [get_ports {CR_A[0]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports reset]
set_drive 1  [get_ports {IM_Q[23]}]
set_drive 1  [get_ports {IM_Q[22]}]
set_drive 1  [get_ports {IM_Q[21]}]
set_drive 1  [get_ports {IM_Q[20]}]
set_drive 1  [get_ports {IM_Q[19]}]
set_drive 1  [get_ports {IM_Q[18]}]
set_drive 1  [get_ports {IM_Q[17]}]
set_drive 1  [get_ports {IM_Q[16]}]
set_drive 1  [get_ports {IM_Q[15]}]
set_drive 1  [get_ports {IM_Q[14]}]
set_drive 1  [get_ports {IM_Q[13]}]
set_drive 1  [get_ports {IM_Q[12]}]
set_drive 1  [get_ports {IM_Q[11]}]
set_drive 1  [get_ports {IM_Q[10]}]
set_drive 1  [get_ports {IM_Q[9]}]
set_drive 1  [get_ports {IM_Q[8]}]
set_drive 1  [get_ports {IM_Q[7]}]
set_drive 1  [get_ports {IM_Q[6]}]
set_drive 1  [get_ports {IM_Q[5]}]
set_drive 1  [get_ports {IM_Q[4]}]
set_drive 1  [get_ports {IM_Q[3]}]
set_drive 1  [get_ports {IM_Q[2]}]
set_drive 1  [get_ports {IM_Q[1]}]
set_drive 1  [get_ports {IM_Q[0]}]
set_drive 1  [get_ports {CR_Q[12]}]
set_drive 1  [get_ports {CR_Q[11]}]
set_drive 1  [get_ports {CR_Q[10]}]
set_drive 1  [get_ports {CR_Q[9]}]
set_drive 1  [get_ports {CR_Q[8]}]
set_drive 1  [get_ports {CR_Q[7]}]
set_drive 1  [get_ports {CR_Q[6]}]
set_drive 1  [get_ports {CR_Q[5]}]
set_drive 1  [get_ports {CR_Q[4]}]
set_drive 1  [get_ports {CR_Q[3]}]
set_drive 1  [get_ports {CR_Q[2]}]
set_drive 1  [get_ports {CR_Q[1]}]
set_drive 1  [get_ports {CR_Q[0]}]
